### ISSUE TITLE
Organise

### ISSUE THREAD

**Issue by stevelinton** [OpenDreamKit/gap-demos#2]
We should probably sort the notebooks into folders depends on which GAP kernel they needs -- master, HPCGAP or 4.10.2.

I've put my GAP code in a gap/ directory. 

Nothing works yet. Get back to this in a few hours, I hope.

**Comment by olexandr-konovalov** [comment]
Good idea. And where to put `.g` files needed for notebooks from `gap` ? Should there be a separate subdirectory for each notebook needing extra `.g` files?

**Comment by stevelinton** [comment]
I think I'd put all the .g files in a single directory. I expect to share some utility routines.

**Comment by olexandr-konovalov** [comment]
This may be closed.

**Comment by olexandr-konovalov** [comment]
This may be closed.
